output_path: "/scratch/indikar_root/indikar1/shared_data/adapter_clean_up/"
fastq_paths: "config/fastq_paths.txt"
dorado_min_qscore: 7
fastqc_adapters: "config/adapter_list.txt"
fastqc_contaminants: "config/contaminant_list.txt"
barcode_path: "config/barcodes.txt"
n_mismatches: 3
threads: 36
