output_path: "/scratch/indikar_root/indikar1/shared_data/re-basecall/"
pod5_paths: "config/pod5_paths.txt"
dorado_path: "/nfs/turbo/umms-indikar/shared/projects/poreC/data/dorado/dorado-0.5.3-linux-x64/bin/dorado"
dorado_model: "/nfs/turbo/umms-indikar/shared/projects/poreC/data/dorado/models/dna_r10.4.1_e8.2_400bps_sup@v4.2.0"
dorado_min_qscore: 7
fastqc_adapters: "config/adapter_list.txt"
fastqc_contaminants: "config/contaminant_list.txt"
barcode_path: "config/barcodes.txt"
n_mismatches: 3
threads: 36
mapq_threshold: 20
